connections {
    pqgm-ikev2 {
        version = 2
        local_addrs = 172.28.0.20
        # SM2-KEM 先，ML-KEM 后
        proposals = aes256-sha256-x25519-ke1_sm2kem-ke2_mlkem768

        local {
            auth = pubkey
            certs = signCert.pem
            id = responder-sign.pqgm.test
        }

        remote {
            auth = pubkey
            id = initiator-sign.pqgm.test
        }

        children {
            ipsec {
                local_ts = 10.2.0.0/16
                remote_ts = 10.1.0.0/16
                esp_proposals = aes256gcm16-sha256
            }
        }
    }
}

secrets {
    sign { file = signKey.pem }
    enc { file = encKey.pem }
}
