# PQ-GM-IKEv2 Docker Test - Responder
# IP: 172.30.0.20 -> 172.30.0.10

connections {
    pqgm-5rtt-mldsa {
        version = 2
        local_addrs = 172.30.0.20
        remote_addrs = 172.30.0.10
        proposals = aes256-sha256-x25519-ke1_sm2kem-ke2_mlkem768

        local {
            auth = pubkey
            id = responder.pqgm.test
            certs = responder_hybrid_cert.pem
        }

        remote {
            auth = pubkey
            id = initiator.pqgm.test
            cacerts = mldsa_ca.pem
        }

        children {
            net {
                local_ts = 10.2.0.0/16
                remote_ts = 10.1.0.0/16
                esp_proposals = aes256gcm16-sha256
                start_action = none
            }
        }
    }

    pqgm-5rtt-gm-symm {
        version = 2
        local_addrs = 172.30.0.20
        remote_addrs = 172.30.0.10
        proposals = sm4-hmacsm3-prfsm3-x25519-ke1_sm2kem-ke2_mlkem768

        local {
            auth = pubkey
            id = responder.pqgm.test
            certs = responder_hybrid_cert.pem
        }

        remote {
            auth = pubkey
            id = initiator.pqgm.test
            cacerts = mldsa_ca.pem
        }

        children {
            net {
                local_ts = 10.2.0.0/16
                remote_ts = 10.1.0.0/16
                esp_proposals = aes256gcm16
                start_action = none
            }
        }
    }
}

secrets {
    mldsa-key {
        id = responder.pqgm.test
        file = responder_mldsa_key.bin
    }
    sm2-enc {
        id = responder.pqgm.test
        file = enc_key.pem
    }
}
