charon {
    load_modular = yes
    accept_private_algs = yes
    
    # Relax certificate constraints
    x509 {
        enforce_critical = no
    }
    
    filelog {
        stdout {
            default = 1
            ike = 3
            cfg = 2
            net = 0
        }
    }
    
    plugins {
        include /usr/local/etc/strongswan.d/charon/*.conf
    }
}
include /usr/local/etc/strongswan.d/*.conf
