charon {
    load_modular = yes
    accept_private_algs = yes

    # Relax certificate constraints
    x509 {
        enforce_critical = no
    }

    filelog {
        stdout {
            default = 2
            ike = 3
            cfg = 2
            net = 2
            lib = 2
        }
    }

    plugins {
        include /usr/local/etc/strongswan.d/charon/*.conf
    }
}
include /usr/local/etc/strongswan.d/*.conf
