connections {
    pqgm-ikev2 {
        version = 2
        local_addrs = 172.28.0.20
        remote_addrs = 172.28.0.10
        proposals = aes256-sha256-x25519

        local {
            auth = psk
            id = responder.pqgm.test
        }

        remote {
            auth = psk
            id = initiator.pqgm.test
        }

        children {
            ipsec {
                local_ts = 10.2.0.0/16
                remote_ts = 10.1.0.0/16
                esp_proposals = aes256gcm16-sha256
                start_action = none
            }
        }
    }
}

secrets {
    ike-psk {
        id = responder.pqgm.test
        secret = "PQGM-Test-PSK-2026"
    }
    ike-psk-i {
        id = initiator.pqgm.test
        secret = "PQGM-Test-PSK-2026"
    }
}
